name: Run Cypress Tests Daily (Parallel + Report)

# Uncomment to run on schedule every day at 10:00 AM Nepal time (UTC+5:45 → cron in UTC)
# schedule:
#   - cron: '15 4 * * *'  # 10:00 AM Nepal time

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests in parallel with Mochawesome
        run: npx cypress run --record --parallel --group "Daily Run" || echo "Cypress exited with code $?"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: List report files (debug)
        run: ls -la cypress/reports/mochawesome/ || echo "No files found in cypress/reports/mochawesome/"

      - name: Upload Mochawesome JSON reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-json-${{ matrix.containers }}
          path: cypress/reports/mochawesome/*.json
          if-no-files-found: ignore

  merge-reports:
    runs-on: ubuntu-latest
    needs: cypress-run
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Download Mochawesome JSON reports
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: mochawesome-json-*
          merge-multiple: true

      - name: Move JSON reports to correct directory
        run: |
          mkdir -p cypress/reports/mochawesome
          mv artifacts/mochawesome-json-*/*.json cypress/reports/mochawesome/ || echo "No JSON files found"

      - name: List report files (debug)
        run: ls -la cypress/reports/mochawesome/ || echo "No files found in cypress/reports/mochawesome/"

      - name: Merge and generate Mochawesome reports
        run: |
          if ls cypress/reports/mochawesome/*.json >/dev/null 2>&1; then
            npx mochawesome-merge cypress/reports/mochawesome/*.json > cypress/reports/mochawesome/mochawesome.json
            npx marge cypress/reports/mochawesome/mochawesome.json --reportDir cypress/reports/mochawesome --reportFilename index.html
          else
            echo "No JSON files found in cypress/reports/mochawesome/. Skipping merge."
          fi

      - name: Upload Mochawesome HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report-${{ github.run_number }}
          path: cypress/reports/mochawesome/index.html
          if-no-files-found: ignore

      - name: Upload Cypress screenshots (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Cypress screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload Cypress videos (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Cypress Videos
          path: cypress/videos
          if-no-files-found: ignore

      - name: Verify CYPRESS_API_KEY
        env:
          CYPRESS_API_KEY: ${{ secrets.CYPRESS_API_KEY }}
        run: |
          if [ -n "$CYPRESS_API_KEY" ]; then
            echo "CYPRESS_API_KEY is set (length: ${#CYPRESS_API_KEY} characters)"
          else
            echo "CYPRESS_API_KEY is not set"
          fi
