name: Run Cypress Tests Daily (Parallel + Report)

# Uncomment to run on schedule every day at 10:00 AM Nepal time (UTC+5:45 → cron in UTC)
# schedule:
#   - cron: '15 4 * * *'  # 10:00 AM Nepal time

# Allow manual triggering and on push
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests in parallel with Mochawesome
        run: npx cypress run --record --parallel --group "Daily Run"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Create report directory
        run: mkdir -p reports/mochawesome

      - name: Merge and generate Mochawesome reports
        if: always()
        run: |
          npx mochawesome-merge cypress/reports/mochawesome/*.json > reports/mochawesome/mochawesome.json
          npx marge reports/mochawesome/mochawesome.json --reportDir reports/mochawesome --reportFilename index.html

      - name: Upload Mochawesome HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report-${{ github.run_number }}
          path: reports/mochawesome/index.html

      - name: Upload Cypress screenshots (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Cypress screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Cypress Videos
          path: cypress/videos
