name: Run Cypress Tests Daily (Parallel + Report)

# Run on schedule every day at 11:15 AM Nepal Time (UTC+5:45 → 5:30 AM UTC)
on:
  schedule:
    - cron: '50 5 * * *' # 5:30 AM UTC = 11:15 AM Nepal Time

# Commented out for scheduled run only
# on:
#   push:
#     branches:
#       - "**"
#   workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Enable pushing changes

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests in parallel with Mochawesome
        run: npx cypress run --record --parallel --group "Daily Run" --reporter cypress-mochawesome-reporter || echo "Cypress exited with code $?"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Verify CYPRESS_RECORD_KEY
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        run: |
          if [ -n "$CYPRESS_RECORD_KEY" ]; then
            echo "CYPRESS_RECORD_KEY is set (length: ${#CYPRESS_RECORD_KEY} characters)"
          else
            echo "CYPRESS_RECORD_KEY is not set"
          fi
        shell: /usr/bin/bash -e {0}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: List report files (debug)
        run: |
          if ls cypress/reports/mochawesome/*.json >/dev/null 2>&1; then
            echo "JSON files found:"
            ls -la cypress/reports/mochawesome/*.json
            echo "Checking JSON file contents:"
            for file in cypress/reports/mochawesome/*.json; do
              echo "Content of $file:"
              cat "$file" || echo "Failed to read $file"
              jq . "$file" >/dev/null 2>&1 && echo "$file is valid JSON" || echo "$file is invalid JSON"
            done
          else
            echo "No JSON files found in cypress/reports/mochawesome/"
          fi
          echo "Listing all files in cypress/reports/mochawesome/:"
          ls -la cypress/reports/mochawesome/
        shell: /usr/bin/bash -e {0}

      - name: Upload Mochawesome JSON reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-json-${{ matrix.containers }}
          path: cypress/reports/mochawesome/*.json
          if-no-files-found: ignore

  merge-reports:
    runs-on: ubuntu-latest
    needs: cypress-run
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Enable pushing changes

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Download Mochawesome JSON reports
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: mochawesome-json-*
          merge-multiple: true

      - name: Move JSON reports to correct directory
        run: |
          mkdir -p cypress/reports/mochawesome
          mv artifacts/mochawesome-json-*/*.json cypress/reports/mochawesome/ || echo "No JSON files found"
        shell: /usr/bin/bash -e {0}

      - name: List report files (debug)
        run: |
          if ls cypress/reports/mochawesome/*.json >/dev/null 2>&1; then
            echo "JSON files found:"
            ls -la cypress/reports/mochawesome/*.json
            echo "Checking JSON file contents:"
            for file in cypress/reports/mochawesome/*.json; do
              echo "Content of $file:"
              cat "$file" || echo "Failed to read $file"
              jq . "$file" >/dev/null 2>&1 && echo "$file is valid JSON" || echo "$file is invalid JSON"
            done
          else
            echo "No JSON files found in cypress/reports/mochawesome/"
          fi
          echo "Listing all files in cypress/reports/mochawesome/:"
          ls -la cypress/reports/mochawesome/
        shell: /usr/bin/bash -e {0}

      - name: Merge and generate Mochawesome reports
        run: |
          if ls cypress/reports/mochawesome/*.json >/dev/null 2>&1; then
            echo "Merging JSON files..."
            npx mochawesome-merge cypress/reports/mochawesome/*.json > cypress/reports/mochawesome/mochawesome.json
            echo "Generating HTML report..."
            npx marge cypress/reports/mochawesome/mochawesome.json --reportDir cypress/reports/mochawesome --reportFilename index.html
            echo "Waiting for file generation (5 seconds)..."
            sleep 5
          else
            echo "No JSON files found in cypress/reports/mochawesome/. Skipping merge."
          fi
        shell: /usr/bin/bash -e {0}

      - name: Commit and push Mochawesome report
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          if [ -f "cypress/reports/mochawesome/index.html" ]; then
            git add cypress/reports/mochawesome/index.html
            git commit -m "Add Mochawesome report from run ${{ github.run_number }}" || echo "No changes to commit"
            git push
          else
            echo "index.html not found, skipping commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: /usr/bin/bash -e {0}

      - name: Upload Mochawesome HTML Report (optional backup)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report-${{ github.run_number }}
          path: cypress/reports/mochawesome/index.html
          if-no-files-found: ignore

      - name: Upload Cypress screenshots (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Cypress screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload Cypress videos (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Cypress Videos
          path: cypress/videos
          if-no-files-found: ignore

      - name: Test(Cypress)
        uses: cypress-io/github-action@v4
        env:
          TZ: Asia/Kathmandu
